#!/usr/bin/env python3
"""
Oregon campaign finance digest generator.
Runs the pre-analysis aggregator and calls Claude to produce a formatted
editorial digest ready for publication.

Usage:
    python digest.py                        # last 7 days (default)
    python digest.py --days 30
    python digest.py --from 04/01/2026 --to 04/30/2026
    python digest.py --output digest.md    # also write to file
    python digest.py --db path/to/file.db
"""

import argparse
import sqlite3
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

try:
    import anthropic
except ImportError:
    print("Missing dependency. Run: pip install anthropic")
    sys.exit(1)

sys.path.insert(0, str(Path(__file__).parent))
try:
    from analyze import build_report, load_thresholds, load_tier_lookup
except ImportError as e:
    print(f"Could not import analyze.py: {e}")
    sys.exit(1)

DEFAULT_DB        = Path(__file__).parent / "campaign_finance.db"
DEFAULT_WATCHLIST = Path(__file__).parent / "watchlist.yaml"
MODEL             = "claude-opus-4-7"

SYSTEM_PROMPT = """\
You are an editorial assistant for a local government accountability publication \
covering Salem, Marion County, and Polk County, Oregon. Your job is to write \
concise, accurate campaign finance digests for engaged local readers — people \
who care about democracy, local politics, and following the money.

You will receive a pre-computed data summary from our campaign finance database. \
The summary was generated by a Python analysis script that queried the Oregon \
Secretary of State's ORESTAR system. Races are grouped into three tiers — \
statewide, legislative, and local — and labeled as such in the data. The data \
covers transactions filed during the period; transaction date and filed date may \
differ by up to 30 days (7 days in the final 6 weeks before an election).

Your role is to interpret, contextualize, and editorialize — not to recompute \
the numbers. The arithmetic is already done. Focus on what the patterns mean, \
why amounts are notable given Oregon's no-contribution-limits environment, and \
what questions a reporter should follow up on.

Produce a digest in exactly this format:

---
### OREGON CAMPAIGN FINANCE — [JURISDICTION] — [DATE RANGE]

**One-sentence summary of the most significant local money movement this period.**

---

#### 🏛 Statewide
*Governor and other state-level races — brief context only. Lead with the most \
newsworthy statewide item, then move on. Do not let gubernatorial dollar volume \
crowd out local coverage.*

**💰 Contributions** *(2–3 items maximum)*
- Committee / race: amount, donor, type — why it matters (one line)

**💸 Expenditures** *(1–2 items, omit section entirely if nothing notable)*
- Committee: amount, vendor — why it matters (one line)

---

#### 🗳 Legislative
*Oregon House and Senate districts covering the watchlist area.*

The data summary includes two subsections you must use:
1. "PAC / COMMITTEE MONEY INTO WATCHLIST LEGISLATIVE RACES" — direct PAC contributions \
to watchlist candidates. These are always a top item regardless of dollar size; \
they reveal which interest groups are picking sides in district races.
2. "CAUCUS PAC ACCUMULATION" — PACs funded by multiple candidate/legislative committees. \
Treat any accumulation PAC with $50K+ or 3+ sources as a lead item; name the \
destination PAC, the contributing committees, the total, and note which watchlist \
districts it is expected to target based on the contributor geography.

**💰 Contributions** *(2–4 items; lead with PAC flows if present)*
- Committee / race: amount, donor, type — why it matters (one line)

**💸 Expenditures** *(1–3 items, omit section if nothing notable)*
- Committee: amount, vendor — why it matters (one line)

---

#### 🏘 Local
*County commissioners, mayor, city council races. This is the primary coverage \
focus — give it the most space.*

**💰 Contributions** *(2–5 items)*
- Committee / race: amount, donor, type — why it matters (one line)

**💸 Expenditures** *(1–3 items, omit section if nothing notable)*
- Committee: amount, vendor — why it matters (one line)

---

#### 🚩 Flags & Anomalies
Include every item from the FLAGS section of the data summary. Group by flag \
type. If flags section is empty, write "None this period."

---

#### 🧵 Threads to Pull
2–3 specific follow-up angles. Prioritize local and legislative leads over \
statewide ones. Be concrete — name the committee, donor, or vendor.

---

#### ⚙️ Data Notes
Filing lag reminders, caveats, missing data.
---

Important guidelines:
- Use the [JURISDICTION] and [DATE RANGE] values provided in the user message
- Do not invent or speculate about data not present in the summary
- Do not editorialize about candidates' politics — only about money patterns
- Oregon has no contribution limits; note when amounts are large in absolute terms
- If a tier has no watchlist activity this period, write "Nothing filed this period."
- Keep bullets tight: one or two lines maximum
"""


def _to_iso(s: str) -> str:
    """Normalize MM/DD/YYYY → YYYY-MM-DD; pass through if already ISO."""
    try:
        return datetime.strptime(s, "%m/%d/%Y").strftime("%Y-%m-%d")
    except ValueError:
        return s


def _jurisdiction_label(watchlist_path: Path) -> str:
    """Derive a short jurisdiction label from the unique jurisdictions in the watchlist."""
    try:
        import yaml as _yaml
        with open(watchlist_path) as f:
            raw = _yaml.safe_load(f)
        jurisdictions = sorted({
            str(r.get("jurisdiction", ""))
            for r in raw.get("races", [])
            if r.get("jurisdiction") and str(r.get("jurisdiction")).lower() != "oregon"
        })
        if not jurisdictions:
            return "Oregon"
        if len(jurisdictions) <= 3:
            return " / ".join(jurisdictions)
        # Summarise when there are many distinct local jurisdictions
        counties = [j for j in jurisdictions if "county" in j.lower()]
        return f"{counties[0].split()[0]} area" if counties else f"{jurisdictions[0]} area"
    except Exception:
        return "Oregon"


def run_digest(from_date: str, to_date: str, db_path: Path, watchlist_path: Path) -> str:
    """Build the pre-analysis report, call Claude, return full digest text."""
    from_date = _to_iso(from_date)
    to_date   = _to_iso(to_date)
    conn = sqlite3.connect(db_path)
    thresholds  = load_thresholds(watchlist_path)
    tier_lookup = load_tier_lookup(watchlist_path)

    print("[digest] Running pre-analysis…", file=sys.stderr)
    report = build_report(conn, from_date, to_date, thresholds, tier_lookup)
    conn.close()

    jurisdiction = _jurisdiction_label(watchlist_path)
    print(f"[digest] Jurisdiction: {jurisdiction}", file=sys.stderr)

    from analyze import fmt_date as _fmt
    date_range = f"{_fmt(from_date)} – {_fmt(to_date)}"
    user_message = (
        f"Produce a campaign finance digest for the period {from_date} to {to_date}.\n"
        f"Use [JURISDICTION] = \"{jurisdiction}\" and [DATE RANGE] = \"{date_range}\" "
        f"in the digest header.\n\n"
        f"Here is the pre-computed data summary:\n\n{report}"
    )

    client = anthropic.Anthropic()

    print(f"[digest] Calling {MODEL} (streaming)…\n", file=sys.stderr)

    parts = []
    with client.messages.stream(
        model=MODEL,
        max_tokens=4096,
        thinking={"type": "adaptive"},
        system=[{
            "type": "text",
            "text": SYSTEM_PROMPT,
            "cache_control": {"type": "ephemeral"},
        }],
        messages=[{"role": "user", "content": user_message}],
    ) as stream:
        for chunk in stream.text_stream:
            print(chunk, end="", flush=True)
            parts.append(chunk)
        final = stream.get_final_message()

    usage = final.usage
    cache_read    = getattr(usage, "cache_read_input_tokens", 0) or 0
    cache_written = getattr(usage, "cache_creation_input_tokens", 0) or 0
    print(f"\n\n[digest] input: {usage.input_tokens:,}  output: {usage.output_tokens:,}", file=sys.stderr)
    if cache_read or cache_written:
        print(f"[digest] cache read: {cache_read:,}  cache write: {cache_written:,}", file=sys.stderr)

    return "".join(parts)


def parse_args():
    p = argparse.ArgumentParser(description="Generate editorial digest from campaign finance data")
    p.add_argument("--days",  type=int, default=7,
                   help="Number of days back to analyze (default: 7)")
    p.add_argument("--from",  dest="from_date", metavar="MM/DD/YYYY",
                   help="Filed-date range start (overrides --days)")
    p.add_argument("--to",    dest="to_date",   metavar="MM/DD/YYYY",
                   help="Filed-date range end (default: today)")
    p.add_argument("--db",    default=str(DEFAULT_DB), metavar="PATH",
                   help=f"SQLite database path (default: {DEFAULT_DB})")
    p.add_argument("--watchlist", default=str(DEFAULT_WATCHLIST), metavar="PATH",
                   help=f"Watchlist YAML path (default: {DEFAULT_WATCHLIST})")
    p.add_argument("--output", metavar="PATH",
                   help="Write digest to this file in addition to stdout")
    return p.parse_args()


def main():
    args = parse_args()

    today = date.today()
    to_date   = args.to_date   or today.strftime("%m/%d/%Y")
    from_date = args.from_date or (today - timedelta(days=args.days)).strftime("%m/%d/%Y")

    db_path = Path(args.db)
    if not db_path.exists():
        print(f"Database not found: {db_path}", file=sys.stderr)
        print("Run collector.py first to populate the database.", file=sys.stderr)
        sys.exit(1)

    print(f"[digest] Period:   {from_date} → {to_date}", file=sys.stderr)
    print(f"[digest] Database: {db_path}", file=sys.stderr)
    print(f"[digest] Model:    {MODEL}", file=sys.stderr)
    print(file=sys.stderr)

    digest = run_digest(from_date, to_date, db_path, Path(args.watchlist))

    if args.output:
        out_path = Path(args.output)
        out_path.write_text(digest)
        print(f"[digest] Saved to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
